Reproduce error:
info building @opam/dot-merlin-reader@opam:4.1@120afa42
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @esy-ocaml/reason@3.7.0
    # esy-build-package: pwd: /Users/yawar/.esy/source/i/esy_ocaml__s__reason__3.7.0__9ed0eb4e
    # esy-build-package: running: 'dune' 'build' '-p' 'reason'
        ocamlopt src/generate/select.exe (exit 2)
    (cd /Users/yawar/.esy/3/b/esy_ocaml__s__reason-3.7.0-7c954828/default && /Users/yawar/.esy/3__________________________________________________________________/i/ocaml-4.10.2000-302fdf3c/bin/ocamlopt.opt -w -40 -g -o src/generate/select.exe src/generate/.select.eobjs/native/select.cmx)
    File "_none_", line 1:
    Error: No implementations provided for the following modules:
             Str referenced from src/generate/.select.eobjs/native/select.cmx
    File "src/reason-merlin/dune", line 13, characters 12-32:
    13 |  (libraries compiler-libs.common merlin-extend reason))
                     ^^^^^^^^^^^^^^^^^^^^
    Error: Library "compiler-libs.common" not found.
    Hint: try:
      dune external-lib-deps --missing -p reason @install
    File "src/vendored-ocaml-migrate-parsetree-v1.8.0/src/dune", line 9, characters 12-32:
    9 |  (libraries compiler-libs.common result ppx_derivers)
                    ^^^^^^^^^^^^^^^^^^^^
    Error: Library "compiler-libs.common" not found.
    Hint: try:
      dune external-lib-deps --missing -p reason @install
    File "src/vendored-ocaml-migrate-parsetree-v1.8.0/tools/dune", line 3, characters 33-55:
    3 |  (libraries compiler-libs.common compiler-libs.bytecomp)
                                         ^^^^^^^^^^^^^^^^^^^^^^
    Error: Library "compiler-libs.bytecomp" not found.
    Hint: try:
      dune external-lib-deps --missing -p reason @install
    error: command failed: 'dune' 'build' '-p' 'reason' (exited with 1)
    esy-build-package: exiting with errors above...

  building @esy-ocaml/reason@3.7.0